//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerEntity
    {
        public int AnswerId { get; set; }
        public string Title { get; set; }
        public Nullable<int> PollId { get; set; }
    }
}
