//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVoteEntities : DbContext
    {
        public EVoteEntities()
            : base("name=EVoteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PollEntity> PollEntities { get; set; }
        public virtual DbSet<AnswerEntity> AnswerEntities { get; set; }
        public virtual DbSet<QuestionEntity> QuestionEntities { get; set; }
        public virtual DbSet<UserEntity> UserEntities { get; set; }
    }
}
