//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatEntity
    {
        public int StatId { get; set; }
        public Nullable<int> PollId { get; set; }
        public Nullable<int> AnswerOneId { get; set; }
        public Nullable<int> AnswerTwoId { get; set; }
        public Nullable<int> AnswerThreeId { get; set; }
        public Nullable<int> AnswerFourId { get; set; }
    }
}
